### ISSUE TITLE
Exception parsing OSGi MANIFEST

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-cbi/org.eclipse.cbi#158] opened 2022-06-26 18:44 UTC
The log attached to https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/issues/5 has quite some of the following Tycho errors. The CBI plugin wrongly parses *.jar.asc files in https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/maven-plugins/eclipse-cbi-plugin/src/main/java/org/eclipse/cbi/mojo/AbstractPluginScannerMojo.java#L57

```
org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/jenkins/agent/workspace/I-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/target/repository/plugins/net.bytebuddy.byte-buddy_1.12.9.jar.asc: The manifest line "-----BEGIN PGP SIGNATURE-----" is invalid; it has no colon ':' character after the header key.
    at org.eclipse.tycho.core.osgitools.OsgiManifest.<init> (OsgiManifest.java:47)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.parse (OsgiManifest.java:146)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFile (DefaultBundleReader.java:102)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromFile (DefaultBundleReader.java:79)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest (DefaultBundleReader.java:65)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest (DefaultBundleReader.java:54)
    at org.eclipse.cbi.mojo.AbstractPluginScannerMojo.execute (AbstractPluginScannerMojo.java:55)
    at org.eclipse.cbi.mojo.TestPropertiesMojo.execute (TestPropertiesMojo.java:41)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.osgi.framework.BundleException: The manifest line "-----BEGIN PGP SIGNATURE-----" is invalid; it has no colon ':' character after the header key.
    at org.eclipse.osgi.util.ManifestElement.parseBundleManifest (ManifestElement.java:527)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.<init> (OsgiManifest.java:43)
    at org.eclipse.tycho.core.osgitools.OsgiManifest.parse (OsgiManifest.java:146)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFile (DefaultBundleReader.java:102)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromFile (DefaultBundleReader.java:79)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest (DefaultBundleReader.java:65)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest (DefaultBundleReader.java:54)
    at org.eclipse.cbi.mojo.AbstractPluginScannerMojo.execute (AbstractPluginScannerMojo.java:55)
    at org.eclipse.cbi.mojo.TestPropertiesMojo.execute (TestPropertiesMojo.java:41)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by iloveeclipse** [comment] 2022-07-23 11:36
See https://github.com/eclipse/tycho/issues/1181.

The problem is still there in platform builds.

**Comment by Bananeweizen** [comment] 2022-07-23 15:40
I'm not sure who could create a new version of the maven plugin. Until then the fix will not make it into any build, I guess. Or are there snapshot builds that could be referenced instead?

**Comment by mickaelistria** [comment] 2022-07-26 08:10
> I'm not sure who could create a new version of the maven plugin.

I suspect it's "only" a matter of submitting a PR to use a non-snapshot version; get it merged and run a build on CI to deploy it to repo.eclipse.org, just like it's done for snapshots ; there is usually no extra process for publishing to repo.eclipse.org between snapshots and release.

**Comment by jukzi** [comment] 2022-10-14 06:05
please reopen:
https://download.eclipse.org/eclipse/downloads/drops4/I20221013-1800/buildlogs/mb060_run-maven-build_output.txt
`org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/jenkins/agent/workspace/Builds/I-build-4.26/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/target/repository/plugins/net.bytebuddy.byte-buddy_1.12.13.jar.asc: The manifest line "-----BEGIN PGP SIGNATURE-----" is invalid; it has no colon ':' character after the header key.
`
for:

- net.bytebuddy.byte-buddy_1.12.13.jar.asc
- org.mockito.mockito-core_4.7.0.jar.asc
- org.apache.commons.commons-fileupload_1.4.0.jar.asc
- org.objenesis_3.2.0.jar.asc
- net.bytebuddy.byte-buddy-agent_1.12.13.jar.asc
- junit-jupiter-api_5.9.1.jar.asc
- assertj-core_3.23.1.jar.asc

**Comment by mbarbero** [comment] 2022-10-14 07:49
> please reopen

To have this fixed, cbi plugin would need to move to Tycho 3.0 and as such would require JDK17 for building. 

If we do that, we need to ensure that the [signing services part](https://github.com/eclipse-cbi/org.eclipse.cbi/tree/main/webservice) stays on jdk11, otherwise, it would re-open https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2035#note_1024297

**Comment by mbarbero** [comment] 2022-10-14 07:49
help wanted on this one.

**Comment by Bananeweizen** [comment] 2022-10-26 07:34
@mbarbero I don't fully understand your above comment regarding Tycho 3.0. Shouldn't it be sufficient to build the current git head as is without further changes? I thought the problem is rather that someone needs to actually deploy that jar afterwards, and I have no idea who that would be.

**Comment by akurtakov** [comment] 2023-01-03 13:09
Main branch now is moved to Tycho 3.0.0 and Java 17 so is there anything else needed here?

**Comment by akurtakov** [comment] 2023-01-23 08:27
Seems that no one has issues still as there have been no reply.

**Closed by akurtakov** 2023-01-23 08:27 UTC
Labels: help wanted
